local L = {}

L.langs = {
    en = "ENGLISH",
    fr = "FRENCH",
    es = "SPANISH",
    zh = "CHINESE",
    ko = "KOREAN",
}

L.dict = {
    en = {
        -- UI List
        title_nearby = "NEARBY PALS",
        col_grade = "G",
        col_score = "SC",
        col_pal = "PAL",
        col_lv = "LV",
        col_sex = "SEX",
        col_dist = "DIST",
        col_h = "H",
        col_a = "A",
        col_d = "D",
        col_passive = "PASSIVE",
        hint_sort = "SORT",
        hint_settings = "SETTINGS",
        hint_next = "NEXT",
        hint_close = "CLOSE",
        msg_no_pals = "No Pals in range",
        msg_no_wild = "No wild Pals in range",
        msg_no_match = "None match the filter — F7 for settings",
        
        -- UI Settings
        title_settings = "SCOUTER SETTINGS",
        opt_language = "LANGUAGE",
        opt_distance = "SCAN DISTANCE",
        opt_refresh = "SCAN REFRESH",
        opt_score = "SCORE MODE",
        opt_filter = "FILTER",
        opt_ownership = "OWNERSHIP",
        opt_watchlist = "WATCHLIST",
        opt_sort = "SORT",
        opt_rows = "PANEL MAX ROWS",
        opt_aimcard = "AIM CARD",
        opt_aimdelay = "AIM CARD DELAY",
        opt_aimsize = "AIM CARD SIZE",
        opt_aimopacity = "AIM CARD OPACITY",
        opt_moveaim = "MOVE AIM CARD",
        opt_panelsize = "PANEL SIZE",
        opt_panelopacity = "PANEL OPACITY",
        opt_movepanel = "MOVE PANEL",
        opt_hideinbase = "HIDE IN BASE",
        opt_reboot = "FORCE RESTART",
        
        val_en = "ENGLISH",
        val_fr = "FRENCH",
        val_es = "SPANISH",
        val_zh = "CHINESE",
        val_ko = "KOREAN",
        
        val_combat = "COMBAT",
        val_work = "WORK",
        val_travel = "TRAVEL",
        val_breeding = "BREEDING",
        val_none = "NONE",
        val_all = "ALL",
        val_wild_only = "WILD ONLY",
        val_owned_only = "OWNED ONLY",
        val_distance = "DISTANCE",
        val_level = "LEVEL",
        val_score = "SCORE",
        val_always = "ALWAYS",
        val_sphere = "SPHERE ONLY",
        val_hover = "HOVER",
        val_focus = "FOCUS",
        val_on = "ON",
        val_off = "OFF",
        val_execute = "EXECUTE",
        
        help_settings = "UP/DOWN: SELECT   LEFT/RIGHT: CYCLE   SPACE: ACTIVATE   BACKSPACE/F7: CLOSE",
        
        -- UI Picker
        title_picker = "SELECT PALS",
        btn_clear = "CLEAR",
        btn_done = "DONE",
        help_picker = "TYPE   UP/DOWN   SPACE: TOGGLE/SELECT   F7: APPLY",
        status_selected = "selected",
        status_max = "MAX",
        status_added = "ADDED",
        status_removed = "REMOVED",

        -- UI Card
        card_stats = "STATS",
        card_active = "ACTIVE SKILLS",
        card_passive = "PASSIVE SKILLS",
        card_work = "WORK SUITABILITY",
        card_no_passive = "No passive skills",
        card_no_active = "No active skills",
        label_attack = "Attack",
        label_defense = "Defense",
        label_work_speed = "Work Speed",
        score_combat = "COMBAT SCORE",
        score_work = "WORK SCORE",
        score_travel = "TRAVEL SCORE",
        score_breeding = "BREEDING SCORE",

        -- Headers
        header_wild = "WILD",
        header_pals = "PALS",
        header_watch = "WATCH",
        header_sort = "SORT",
        header_filter = "FILTER",
        header_page = "PAGE",
        header_scanning = "scanning",
        header_resolving = "resolving",
        msg_no_score_meet = "No %s score meets %s (%d+) — set FILTER OFF",
    },
    fr = {
        -- UI List
        title_nearby = "PALS PROCHES",
        col_grade = "G",
        col_score = "SC",
        col_pal = "PAL",
        col_lv = "NV",
        col_sex = "SEXE",
        col_dist = "DIST",
        col_h = "PV",
        col_a = "ATQ",
        col_d = "DEF",
        col_passive = "PASSIFS",
        hint_sort = "TRIER",
        hint_settings = "RÉGLAGES",
        hint_next = "SUIVANT",
        hint_close = "FERMER",
        msg_no_pals = "Aucun Pal à portée",
        msg_no_wild = "Aucun Pal sauvage à portée",
        msg_no_match = "Aucun ne correspond — F7 pour régler",
        
        -- UI Settings
        title_settings = "RÉGLAGES SCOUTER",
        opt_language = "LANGUE",
        opt_distance = "DIST. DE SCAN",
        opt_refresh = "RAFRAÎCHISSEMENT",
        opt_score = "MODE DE SCORE",
        opt_filter = "FILTRE",
        opt_ownership = "PROPRIÉTAIRE",
        opt_watchlist = "LISTE DE SUIVI",
        opt_sort = "TRI",
        opt_rows = "LIGNES MAX PANEL",
        opt_aimcard = "CARTE DE VISÉE",
        opt_aimdelay = "DÉLAI DE VISÉE",
        opt_aimsize = "TAILLE VISÉE",
        opt_aimopacity = "OPACITÉ VISÉE",
        opt_moveaim = "BOUGER VISÉE",
        opt_panelsize = "TAILLE PANEL",
        opt_panelopacity = "OPACITÉ PANEL",
        opt_movepanel = "BOUGER PANEL",
        opt_hideinbase = "CACHER EN BASE",
        opt_reboot = "FORCER REDEMARRAGE",
        
        val_en = "ANGLAIS",
        val_fr = "FRANÇAIS",
        val_es = "ESPAGNOL",
        val_zh = "CHINOIS",
        val_ko = "CORÉEN",
        
        val_combat = "COMBAT",
        val_work = "TRAVAIL",
        val_travel = "VOYAGE",
        val_breeding = "REPRODUCTION",
        val_none = "AUCUN",
        val_all = "TOUS",
        val_wild_only = "SAUVAGES SEULS",
        val_owned_only = "POSSÉDÉS SEULS",
        val_distance = "DISTANCE",
        val_level = "NIVEAU",
        val_score = "SCORE",
        val_always = "TOUJOURS",
        val_sphere = "SPHERE SEULE",
        val_hover = "SURVOL",
        val_focus = "FOCUS",
        val_on = "ACTIF",
        val_off = "INACTIF",
        val_execute = "EXECUTER",
        
        help_settings = "HAUT/BAS: SELECT.   GAUCHE/DROITE: CHANGER   ESPACE: ACTIVER   RETOUR/F7: FERMER",
        
        -- UI Picker
        title_picker = "SÉLECTION PALS",
        btn_clear = "EFFACER",
        btn_done = "VALIDER",
        help_picker = "ÉCRIRE   HAUT/BAS   ESPACE: COCHER/DÉCOCHER   F7: APPLIQUER",
        status_selected = "sélectionné(s)",
        status_max = "MAX",
        status_added = "AJOUTÉ",
        status_removed = "RETIRÉ",

        -- UI Card
        card_stats = "STATS",
        card_active = "COMPÉTENCES ACTIVES",
        card_passive = "PASSIFS",
        card_work = "APTITUDES AU TRAVAIL",
        card_no_passive = "Aucun passif",
        card_no_active = "Aucune compétence active",
        label_attack = "Attaque",
        label_defense = "Défense",
        label_work_speed = "Vitesse de travail",
        score_combat = "SCORE COMBAT",
        score_work = "SCORE TRAVAIL",
        score_travel = "SCORE EXPLORATION",
        score_breeding = "SCORE ELEVAGE",

        -- Headers
        header_wild = "SAUVAGES",
        header_pals = "TOUS",
        header_watch = "SUIVIS",
        header_sort = "TRI",
        header_filter = "FILTRE",
        header_page = "PAGE",
        header_scanning = "analyse",
        header_resolving = "résolution",
        msg_no_score_meet = "Aucun score %s ne satisfait %s (%d+) — désactivez le FILTRE",
    },
    es = {
        -- UI List
        title_nearby = "PALS CERCANOS",
        col_grade = "G",
        col_score = "SC",
        col_pal = "PAL",
        col_lv = "NV",
        col_sex = "SEXO",
        col_dist = "DIST",
        col_h = "PS",
        col_a = "ATQ",
        col_d = "DEF",
        col_passive = "PASIVAS",
        hint_sort = "ORDENAR",
        hint_settings = "AJUSTES",
        hint_next = "SIGUIENTE",
        hint_close = "CERRAR",
        msg_no_pals = "Sin Pals en rango",
        msg_no_wild = "Sin Pals salvajes en rango",
        msg_no_match = "Ninguno coincide — F7 para ajustes",
        
        -- UI Settings
        title_settings = "AJUSTES DE SCOUTER",
        opt_language = "IDIOMA",
        opt_distance = "DIST. DE ESCANEO",
        opt_refresh = "REFRESCO",
        opt_score = "MODE DE PUNTOS",
        opt_filter = "FILTRO",
        opt_ownership = "PROPIEDAD",
        opt_watchlist = "LISTA DE SEGUIM.",
        opt_sort = "ORDEN",
        opt_rows = "FILAS MÁX PANEL",
        opt_aimcard = "TARJETA APUNTADO",
        opt_aimdelay = "RETRASO APUNTADO",
        opt_aimsize = "TAMAÑO APUNTADO",
        opt_aimopacity = "OPACIDAD APUNTADO",
        opt_moveaim = "MOVER APUNTADO",
        opt_panelsize = "TAMAÑO PANEL",
        opt_panelopacity = "OPACIDAD PANEL",
        opt_movepanel = "MOVER PANEL",
        opt_hideinbase = "OCULTAR EN BASE",
        
        val_en = "INGLÉS",
        val_fr = "FRANCÉS",
        val_es = "ESPAÑOL",
        val_zh = "CHINO",
        val_ko = "COREANO",
        
        val_combat = "COMBATE",
        val_work = "TRABAJO",
        val_travel = "VIAJE",
        val_breeding = "CRÍA",
        val_none = "NINGUNO",
        val_all = "TODOS",
        val_wild_only = "SOLO SALVAJES",
        val_owned_only = "SOLO PROPIOS",
        val_distance = "DISTANCIA",
        val_level = "NIVEL",
        val_score = "PUNTOS",
        val_always = "SIEMPRE",
        val_sphere = "SOLO ESFERA",
        val_hover = "APUNTAR",
        val_focus = "ENFOQUE",
        val_on = "SÍ",
        val_off = "NO",
        
        help_settings = "ARR./ABA.: SEL.   IZQ./DER.: CAMBIAR   ESPACIO: ACTIVAR   RETROCESO/F7: CERRAR",
        
        -- UI Picker
        title_picker = "SELECCIÓN PALS",
        btn_clear = "BORRAR",
        btn_done = "HECHO",
        help_picker = "ESCRIBIR   ARR./ABA.   ESPACIO: MARCAR/DESMARCAR   F7: APLICAR",
        status_selected = "seleccionado(s)",
        status_max = "MÁX",
        status_added = "AÑADIDO",
        status_removed = "ELIMINADO",

        -- UI Card
        card_stats = "ESTADÍSTICAS",
        card_active = "HABILIDADES ACTIVAS",
        card_passive = "HABILIDADES PASIVAS",
        card_work = "APTITUDES DE TRABAJO",
        card_no_passive = "Sin habilidades pasivas",
        card_no_active = "Sin habilidades activas",
        label_attack = "Ataque",
        label_defense = "Defensa",
        label_work_speed = "Velocidad de trabajo",
        score_combat = "PUNTOS DE COMBATE",
        score_work = "PUNTOS DE TRABAJO",
        score_travel = "PUNTOS DE VIAJE",
        score_breeding = "PUNTOS DE CRÍA",

        -- Headers
        header_wild = "SALVAJES",
        header_pals = "PALS",
        header_watch = "SEGUIMIENTO",
        header_sort = "ORDEN",
        header_filter = "FILTRO",
        header_page = "PÁGINA",
        header_scanning = "escaneando",
        header_resolving = "resolviendo",
        msg_no_score_meet = "Ningún punto %s cumple con %s (%d+) — desactive el FILTRO",
    },
    zh = {
        -- UI List
        title_nearby = "附近帕鲁",
        col_grade = "级",
        col_score = "评分",
        col_pal = "帕鲁",
        col_lv = "等级",
        col_sex = "性别",
        col_dist = "距离",
        col_h = "血",
        col_a = "攻",
        col_d = "防",
        col_passive = "被动词条",
        hint_sort = "排序",
        hint_settings = "设置",
        hint_next = "下一页",
        hint_close = "关闭",
        msg_no_pals = "范围内无帕鲁",
        msg_no_wild = "范围内无野生帕鲁",
        msg_no_match = "没有匹配 of 帕鲁 — 按 F7 打开设置",
        
        -- UI Settings
        title_settings = "探测器设置",
        opt_language = "语言",
        opt_distance = "扫描距离",
        opt_refresh = "扫描频率",
        opt_score = "评分模式",
        opt_filter = "过滤器",
        opt_ownership = "所有权",
        opt_watchlist = "监视列表",
        opt_sort = "排序方式",
        opt_rows = "面板最大行数",
        opt_aimcard = "准星卡片",
        opt_aimdelay = "准星延迟",
        opt_aimsize = "卡片大小",
        opt_aimopacity = "卡片透明度",
        opt_moveaim = "移动准星卡片",
        opt_panelsize = "面板大小",
        opt_panelopacity = "面板透明度",
        opt_movepanel = "移动面板",
        opt_hideinbase = "基地内隐藏",
        
        val_en = "英文",
        val_fr = "法文",
        val_es = "西班牙文",
        val_zh = "中文",
        val_ko = "韩文",
        
        val_combat = "战斗",
        val_work = "工作",
        val_travel = "旅行",
        val_breeding = "配种",
        val_none = "无",
        val_all = "全部",
        val_wild_only = "仅野生",
        val_owned_only = "仅已捕获",
        val_distance = "距离",
        val_level = "等级",
        val_score = "评分",
        val_always = "总是显示",
        val_sphere = "仅帕鲁球",
        val_hover = "悬停显示",
        val_focus = "聚焦显示",
        val_on = "开启",
        val_off = "关闭",
        
        help_settings = "上下: 选择   左右: 切换   空格: 确认   退格键/F7: 关闭",
        
        -- UI Picker
        title_picker = "选择帕鲁",
        btn_clear = "清空",
        btn_done = "完成",
        help_picker = "输入进行过滤   上下选择   空格: 勾选/取消   F7: 保存",
        status_selected = "已选择",
        status_max = "最大数量",
        status_added = "已添加",
        status_removed = "已移除",

        -- UI Card
        card_stats = "属性状态",
        card_active = "主动技能",
        card_passive = "被动技能",
        card_work = "工作适应性",
        card_no_passive = "无被动技能",
        card_no_active = "无主动技能",
        label_attack = "攻击",
        label_defense = "防御",
        label_work_speed = "工作速度",
        score_combat = "战斗评分",
        score_work = "工作评分",
        score_travel = "旅行评分",
        score_breeding = "配种评分",

        -- Headers
        header_wild = "野生",
        header_pals = "帕鲁",
        header_watch = "监视",
        header_sort = "排序",
        header_filter = "过滤",
        header_page = "页码",
        header_scanning = "扫描中",
        header_resolving = "解析中",
        msg_no_score_meet = "没有 %s 评分符合 %s (%d+) — 请关闭过滤器",
    },
    ko = {
        title_nearby = "주변 팰",
        col_grade = "등급",
        col_score = "점수",
        col_pal = "팰",
        col_lv = "레벨",
        col_sex = "성별",
        col_dist = "거리",
        col_h = "체력",
        col_a = "공격",
        col_d = "방어",
        col_passive = "패시브",
        hint_sort = "정렬",
        hint_settings = "설정",
        hint_next = "다음",
        hint_close = "닫기",
        msg_no_pals = "범위 내에 팰이 없습니다",
        msg_no_wild = "범위 내에 야생 팰이 없습니다",
        msg_no_match = "필터와 일치하는 팰이 없습니다 — F7을 눌러 설정 변경",
        title_settings = "스카우터 설정",
        opt_language = "언어",
        opt_distance = "스캔 거리",
        opt_refresh = "스캔 주기",
        opt_score = "점수 모드",
        opt_filter = "필터",
        opt_ownership = "소유 여부",
        opt_watchlist = "관심 목록",
        opt_sort = "정렬 기준",
        opt_rows = "패널 최대 행수",
        opt_aimcard = "조준 카드",
        opt_aimdelay = "조준 딜레이",
        opt_aimsize = "카드 크기",
        opt_aimopacity = "카드 투명도",
        opt_moveaim = "조준 카드 이동",
        opt_panelsize = "패널 크기",
        opt_panelopacity = "패널 투명도",
        opt_movepanel = "패널 이동",
        opt_hideinbase = "기지 내 숨김",
        val_en = "영어",
        val_fr = "프랑스어",
        val_es = "스페인어",
        val_zh = "중국어",
        val_ko = "한국어",
        val_combat = "전투",
        val_work = "작업",
        val_travel = "이동",
        val_breeding = "교배",
        val_none = "없음",
        val_all = "전체",
        val_wild_only = "야생만",
        val_owned_only = "소유만",
        val_distance = "거리",
        val_level = "레벨",
        val_score = "점수",
        val_always = "항상",
        val_sphere = "스피어만",
        val_hover = "호버",
        val_focus = "포커스",
        val_on = "켜짐",
        val_off = "꺼짐",
        help_settings = "위/아래: 선택   왼쪽/오른쪽: 변경   스페이스: 활성화   백스페이스/F7: 닫기",
        title_picker = "팰 선택",
        btn_clear = "지우기",
        btn_done = "완료",
        help_picker = "검색어 입력   위/아래 이동   스페이스: 선택/취소   F7: 적용",
        status_selected = "선택됨",
        status_max = "최대",
        status_added = "추가됨",
        status_removed = "제거됨",
        card_stats = "능력치",
        card_active = "액티브 스킬",
        card_passive = "패시브 스킬",
        card_work = "작업 적성",
        card_no_passive = "패시브 스킬 없음",
        card_no_active = "액티브 스킬 없음",
        label_attack = "공격력",
        label_defense = "방어력",
        label_work_speed = "작업 속도",
        score_combat = "전투 점수",
        score_work = "작업 점수",
        score_travel = "이동 점수",
        score_breeding = "교배 점수",
        header_wild = "야생",
        header_pals = "팰",
        header_watch = "관심",
        header_sort = "정렬",
        header_filter = "필터",
        header_page = "페이지",
        header_scanning = "스캔 중",
        header_resolving = "해석 중",
        msg_no_score_meet = "만족하는 %s 점수 %s (%d+)가 없습니다 — 필터 끄기",
    }
}

function L.get_current_lang(cfg_lang)
    if cfg_lang and L.dict[cfg_lang] then
        return cfg_lang
    end
    return "en"
end

function L.t(key, cfg_lang)
    local lang = L.get_current_lang(cfg_lang)
    local t_table = L.dict[lang] or L.dict["en"]
    return t_table[key] or L.dict["en"][key] or key
end

return L
